"""empty message

Revision ID: 3b065973c357
Revises: 5c06451a77b7
Create Date: 2020-11-19 11:51:05.550695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b065973c357'
down_revision = '5c06451a77b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'last_update')
    # ### end Alembic commands ###
