"""empty message

Revision ID: 3ba37597af43
Revises: ec65852c33fa
Create Date: 2020-11-11 23:51:11.089337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba37597af43'
down_revision = 'ec65852c33fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'note')
    # ### end Alembic commands ###
