"""empty message

Revision ID: 5c06451a77b7
Revises: 3ba37597af43
Create Date: 2020-11-18 17:31:18.149867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c06451a77b7'
down_revision = '3ba37597af43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gyms', sa.Column('book_before', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gyms', 'book_before')
    # ### end Alembic commands ###
