"""empty message

Revision ID: 777e6c456972
Revises: 
Create Date: 2020-11-01 15:25:05.787061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777e6c456972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('max_booking_length', sa.Integer(), nullable=True),
    sa.Column('max_booking_per_user', sa.Integer(), nullable=True),
    sa.Column('max_time_per_user_per_day', sa.Integer(), nullable=True),
    sa.Column('max_number_per_booking', sa.Integer(), nullable=False),
    sa.Column('max_days_ahead', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('username', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('email', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('role', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gym_admins',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('gym', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gym'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user', 'gym')
    )
    op.create_table('gym_memberships',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('gym', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gym'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user', 'gym')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gym_id', sa.Integer(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('zones')
    op.drop_table('gym_memberships')
    op.drop_table('gym_admins')
    op.drop_table('users')
    op.drop_table('gyms')
    # ### end Alembic commands ###
